#!/usr/bin/env bash
# Congiure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/beni-f permanent;" 
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default


sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
