#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration, good luck for the 8th loop iteration, Best School for the other iterations

i=0
while [ $i -lt 20 ]
do  
    if [ $i -eq 3 ]
       then echo "bad luck from China"
    elif [ $i -eq 8 ]
        then echo "bad luck from Japan"
    elif [ $i -eq 16 ]
        then echo "bad luck from Italy" 
    else
        echo $i
    fi 
    ((i++))
done