#!/usr/bin/bash env
# Block all incoming traffic except 22, 443, 80 tcp ports
sudo apt update
sudo apt install ufw
sudo ufw disable
sudo ufw reset
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
